WINDOW_TITLE = "CONNECT FOUR - ARCADE EDITION"
WINDOW_GEOMETRY = "1100x1200"

COLOR_BG = "#0c0c14"               
COLOR_BG_BOARD = "#05050d"         
COLOR_CABINET = "#ffffff"   

COLOR_CIRCLE_EMPTY = "#131324"     
COLOR_BORDER_EMPTY = "#22223b"     

COLOR_P1_LIGHT = "#ff0055"       
COLOR_P1_DARK = "#990033"        
COLOR_P2_LIGHT = "#0051ff"       
COLOR_P2_DARK = "#050099"        

COLOR_TEXT_NEON = "#0051ff"        
COLOR_TEXT_PINK = "#ff0055"        
COLOR_TEXT_WHITE = "#ffffff"       
COLOR_TEXT_MUTED = "#555577"     

COLOR_BTN_BG = "#181830"
COLOR_BTN_BORDER = "#ffcc00"
COLOR_BTN_ACTIVE = "#ffcc00"

FONT_TITLE = ("ArcadeClassic", 50)      
FONT_LABEL_LARGE = ("ArcadeClassic", 18)
FONT_BTN_SMALL = ("ArcadeClassic", 20)
FONT_LABEL_MEDIUM = ("ArcadeClassic", 21)
FONT_LABEL_SMALL = ("ArcadeClassic", 20)
FONT_BTN_LARGE = ("ArcadeClassic", 22)

TXT_TITLE = "CONNECT 4"
TXT_CREATE_BTN = "[ CREATE GAME ]"
TXT_JOIN_BTN = "[ JOIN ]"
TXT_QUIT_BTN = "[ ABANDON GAME ]"
TXT_MATCH_ID_LABEL = "MATCH ID:"
TXT_LOBBY_STATUS_DEFAULT = "INSERT COIN TO PLAY..."

MSG_CREATING = "CREATING MATCH..."
MSG_JOINING = "CONNECTING TO ROOM {match_id}..."
MSG_WAITING_OPPONENT = "ROOM CREATED! ID: {match_id}\nWAITING FOR OPPONENT..."
MSG_NEW_ROOM_AVAILABLE = "ROOM DETECTED! ID: {match_id}\nENTER ID TO JOIN."
MSG_GAME_STARTED = "STARTING..."
MSG_YOUR_TURN = "YOUR TURN! DROP YOUR COIN"
MSG_WAIT_TURN = "WAITING FOR OPPONENT..."
MSG_REMATCH_WAIT = "WAITING FOR REMATCH..."
MSG_REMATCH_ACCEPTED = "REMATCH ACCEPTED!"
MSG_OPPONENT_ASK_REMATCH = "OPPONENT REQUESTS REMATCH!"

POPUP_TITLE_END = "Game Over"
POPUP_MSG_WIN = "WINNER!\n\nWant a rematch?"
POPUP_MSG_LOSE = "LOOSER!\n\nWant a rematch?"
POPUP_MSG_DRAW = "DRAW!\n\nWant a rematch?"
POPUP_MSG_DISCONNECTED = "WINNER!\n\n!OPPONENT HAS LEFT THE ROOM!"

POPUP_TITLE_REMATCH_CANCEL = "Rematch Cancelled"
POPUP_MSG_REMATCH_CANCEL = "Opponent declined the rematch."

POPUP_TITLE_CHALLENGE = "Challenge Request"
POPUP_MSG_CHALLENGE = "Player {fd} wants to join your game.\nDo you accept the challenge?"

POPUP_TITLE_WARN = "Warning"                                          
POPUP_MSG_INVALID_ID = "Please enter a valid match ID (numbers only)!" 
MSG_REJECTED = "CHALLENGE REJECTED."

CELL_WIDTH = 980 // 7  
CELL_HEIGHT = 810 // 6 
DIAMETER = 112 